name: Deploy S3 to EB

on:
  push:
    branches: [ master ]

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create ZIP deployment package
        run: zip -r deploy_package.zip ./

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::456354563558:user/poseidon9
          aws-region: us-east-1

      - name: Upload package to S3 bucket
        run: aws s3 cp deploy_package.zip s3://python-financial-api/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name Python-Financial-API \
          --source-bundle S3Bucket="python-financial-api",S3Key="deploy_package.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name Pythonfinancialapi-env --version-label "ver-${{ github.sha }}"
